import {
  PartnerId,
  PartnerUser,
  FinancialTransaction,
  DealItem,
  ClientRecord,
  ProjectRecord,
  VultoTapBatch,
  GoalItem,
  ServiceCatalogItem,
  DashboardState,
} from './types';

export const PARTNERS: Record<string, PartnerUser> = {
  felipe: {
    id: 'felipe',
    name: 'Felipe Camargo',
    role: 'Projetos & Estratégia',
    avatarInitials: 'FC',
    whatsapp: '5513982252557',
  },
  pietro: {
    id: 'pietro',
    name: 'Pietro',
    role: 'Parcerias & Comercial',
    avatarInitials: 'P',
    whatsapp: '5521973486125',
  },
};

export const INITIAL_TRANSACTIONS: FinancialTransaction[] = [
  {
    id: 'tx-001',
    date: '2026-10-06',
    description: 'Retainer Mensal — Gestão de Tráfego & Performance',
    clientOrVendor: 'Nexus Capital',
    type: 'income',
    category: 'Retainer Mensal',
    amount: 5800,
    status: 'paid',
    paymentMethod: 'PIX',
    partnerResponsible: 'pietro',
  },
  {
    id: 'tx-002',
    date: '2026-10-05',
    description: 'Setup Plataforma Web & Sistema Interno (Parcela 2/2)',
    clientOrVendor: 'Veritas Construtora',
    type: 'income',
    category: 'Setup & Dev',
    amount: 14500,
    status: 'paid',
    paymentMethod: 'PIX',
    partnerResponsible: 'felipe',
  },
  {
    id: 'tx-003',
    date: '2026-10-04',
    description: 'Lote 120 Cartões NFC Metal Matte Customizados',
    clientOrVendor: 'Grupo Aurora Real Estate',
    type: 'income',
    category: 'Vulto Tap',
    amount: 9800,
    status: 'paid',
    paymentMethod: 'Transferência',
    partnerResponsible: 'pietro',
  },
  {
    id: 'tx-004',
    date: '2026-10-03',
    description: 'Infraestrutura Cloud & Servidores Dedicados',
    clientOrVendor: 'Hetzner & AWS Cloud',
    type: 'expense',
    category: 'Infra & Ferramentas',
    amount: 1240,
    status: 'paid',
    paymentMethod: 'Cartão',
    partnerResponsible: 'felipe',
  },
  {
    id: 'tx-005',
    date: '2026-10-02',
    description: 'Fornecedor de Chips NFC NTAG216 (Importação lote 500un)',
    clientOrVendor: 'NFC Tech Components Ind.',
    type: 'expense',
    category: 'Vulto Tap',
    amount: 3450,
    status: 'paid',
    paymentMethod: 'Transferência',
    partnerResponsible: 'felipe',
  },
  {
    id: 'tx-006',
    date: '2026-10-01',
    description: 'Retainer Mensal — Copywriting & Estrutura de Aquisição',
    clientOrVendor: 'Solares Energia Solar',
    type: 'income',
    category: 'Retainer Mensal',
    amount: 4900,
    status: 'paid',
    paymentMethod: 'PIX',
    partnerResponsible: 'pietro',
  },
  {
    id: 'tx-007',
    date: '2026-10-07',
    description: 'Setup Agente de Inteligência Artificial para Triagem 24/7',
    clientOrVendor: 'Clínica Dr. Marcelo Brandão',
    type: 'income',
    category: 'Setup & Dev',
    amount: 6200,
    status: 'paid',
    paymentMethod: 'PIX',
    partnerResponsible: 'felipe',
  },
  {
    id: 'tx-008',
    date: '2026-10-10',
    description: 'Retainer Mensal — Paid Media & Google Ads B2B',
    clientOrVendor: 'Orbital Tech Logística',
    type: 'income',
    category: 'Retainer Mensal',
    amount: 5200,
    status: 'pending',
    paymentMethod: 'Boleto',
    partnerResponsible: 'pietro',
  },
  {
    id: 'tx-009',
    date: '2026-10-15',
    description: 'Ferramentas de IA & APIs (OpenAI, Gemini API, Claude API)',
    clientOrVendor: 'OpenAI / Google Cloud',
    type: 'expense',
    category: 'Infra & Ferramentas',
    amount: 880,
    status: 'pending',
    paymentMethod: 'Cartão',
    partnerResponsible: 'felipe',
  },
];

export const INITIAL_DEALS: DealItem[] = [
  {
    id: 'deal-101',
    companyName: 'Lumina Odontologia Estética',
    contactName: 'Dra. Amanda Luz',
    service: 'Paid Media + Landing Page de Alta Conversão',
    monthlyValue: 4500,
    setupValue: 5500,
    totalEstimated: 10000,
    stage: 'negotiation',
    probability: 85,
    owner: 'pietro',
    createdAt: '2026-09-28',
    updatedAt: '2026-10-07',
    notes: 'Proposta apresentada. Gostaram da projeção de ROAS. Aguardando validação do sócio financeiro.',
    priority: 'alta',
  },
  {
    id: 'deal-102',
    companyName: 'Vanguard Arquitetura & Interiores',
    contactName: 'Carlos Mendonça',
    service: 'VULTO TAP (Kit Corporativo 80 cartões) + Redesign Web',
    monthlyValue: 0,
    setupValue: 18000,
    totalEstimated: 18000,
    stage: 'proposal',
    probability: 60,
    owner: 'pietro',
    createdAt: '2026-10-02',
    updatedAt: '2026-10-06',
    notes: 'Enviamos o modelo físico de amostra do cartão metal gravado. Reunião de fechamento agendada para sexta.',
    priority: 'alta',
  },
  {
    id: 'deal-103',
    companyName: 'Bunker Investimentos',
    contactName: 'Rodrigo Esteves',
    service: 'Agente de IA 24/7 + Integração CRM & WhatsApp',
    monthlyValue: 2200,
    setupValue: 7500,
    totalEstimated: 9700,
    stage: 'discovery',
    probability: 40,
    owner: 'felipe',
    createdAt: '2026-10-05',
    updatedAt: '2026-10-07',
    notes: 'Briefing técnico alinhado. Triagem inicial necessita de validação prévia de patrimônio líquido investível.',
    priority: 'media',
  },
  {
    id: 'deal-104',
    companyName: 'Kronos Fitness & Suplementação',
    contactName: 'Bruno Alencar',
    service: 'Tráfego Pago Meta Ads & Google Search',
    monthlyValue: 4000,
    setupValue: 3500,
    totalEstimated: 7500,
    stage: 'won',
    probability: 100,
    owner: 'pietro',
    createdAt: '2026-09-20',
    updatedAt: '2026-10-04',
    notes: 'Contrato assinado. Kickoff de alinhamento com Felipe realizado dia 05.',
    priority: 'alta',
  },
  {
    id: 'deal-105',
    companyName: 'Alliance Advocacia Corporativa',
    contactName: 'Fabiana Rossi',
    service: 'Site Institucional Premium + Copywriting Especializado',
    monthlyValue: 0,
    setupValue: 9500,
    totalEstimated: 9500,
    stage: 'lead',
    probability: 25,
    owner: 'pietro',
    createdAt: '2026-10-07',
    updatedAt: '2026-10-07',
    notes: 'Lead recebido via formulário do site. Interesse em autoridade institucional.',
    priority: 'media',
  },
];

export const INITIAL_CLIENTS: ClientRecord[] = [
  {
    id: 'cli-01',
    companyName: 'Nexus Capital Gestão de Recursos',
    legalName: 'Nexus Capital Asset Management Ltda',
    contactName: 'Henrique Vasconcelos',
    email: 'henrique@nexuscapital.com.br',
    phone: '+55 11 98455-1200',
    status: 'active',
    services: ['Paid Media', 'Landing Pages', 'Estratégia'],
    monthlyRetainer: 5800,
    setupPaid: 6500,
    startDate: '2026-04-10',
    renewalDate: '2027-04-10',
    leadOwner: 'pietro',
    health: 'excelente',
    notes: 'ROAS estável em 5.4x. Cliente com alto potencial de expansão para produto institucional.',
  },
  {
    id: 'cli-02',
    companyName: 'Veritas Construtora & Incorporadora',
    legalName: 'Veritas Engenharia e Negócios Ltda',
    contactName: 'Eduardo Guimarães',
    email: 'eduardo@veritaseng.com.br',
    phone: '+55 21 99870-4321',
    status: 'active',
    services: ['Sites & Sistemas', 'Vulto Tap'],
    monthlyRetainer: 0,
    setupPaid: 29000,
    startDate: '2026-07-15',
    leadOwner: 'felipe',
    health: 'excelente',
    notes: 'Entrega da plataforma imobiliária na fase final. Adquiriram 40 cartões Vulto Tap para corretores.',
  },
  {
    id: 'cli-03',
    companyName: 'Solares Energia Solar',
    legalName: 'Solares Soluções Fotovoltaicas Ltda',
    contactName: 'Renata Castro',
    email: 'renata@solaresenergia.com.br',
    phone: '+55 13 99765-8812',
    status: 'active',
    services: ['Copywriting', 'Paid Media'],
    monthlyRetainer: 4900,
    setupPaid: 4500,
    startDate: '2026-05-01',
    renewalDate: '2026-11-01',
    leadOwner: 'pietro',
    health: 'estavel',
    notes: 'CPL médio em R$ 38 no Meta Ads. Foco atual em aumentar taxa de fechamento no comercial.',
  },
  {
    id: 'cli-04',
    companyName: 'Clínica Dr. Marcelo Brandão',
    legalName: 'Brandão Cirurgia & Saúde Integrada',
    contactName: 'Dr. Marcelo Brandão',
    email: 'marcelo@drbrandaocirurgia.com.br',
    phone: '+55 11 97120-9944',
    status: 'onboarding',
    services: ['Inteligência Artificial', 'Paid Media'],
    monthlyRetainer: 3800,
    setupPaid: 6200,
    startDate: '2026-10-01',
    leadOwner: 'felipe',
    health: 'excelente',
    notes: 'Implementando bot de triagem no WhatsApp. Expectativa de reduzir no-show em 40%.',
  },
  {
    id: 'cli-05',
    companyName: 'Grupo Aurora Real Estate',
    legalName: 'Aurora Empreendimentos Imobiliários',
    contactName: 'Patrícia Nogueira',
    email: 'patricia@grupoaurora.com.br',
    phone: '+55 11 98823-4555',
    status: 'active',
    services: ['Vulto Tap (120un)', 'Páginas de Empreendimento'],
    monthlyRetainer: 0,
    setupPaid: 16800,
    startDate: '2026-08-12',
    leadOwner: 'pietro',
    health: 'excelente',
    notes: 'Cartões físicos entregues com sucesso. Feedback excelente da diretoria executiva.',
  },
];

export const INITIAL_PROJECTS: ProjectRecord[] = [
  {
    id: 'proj-01',
    title: 'Plataforma Web Veritas Construtora',
    clientName: 'Veritas Construtora & Incorporadora',
    serviceType: 'Sites & Sistemas',
    leadPartner: 'felipe',
    status: 'review',
    deadline: '2026-10-14',
    progressPercent: 90,
    deliverableLink: 'https://preview.veritas.vultolab.company',
    tasks: [
      { id: 't1', title: 'Arquitetura e modelagem de dados dos empreendimentos', completed: true, assignedTo: 'felipe' },
      { id: 't2', title: 'Integração com simulador de financiamento e WhatsApp', completed: true, assignedTo: 'felipe' },
      { id: 't3', title: 'Otimização Lighthouse 95+ e SEO Técnico', completed: true, assignedTo: 'felipe' },
      { id: 't4', title: 'Revisão final de copy e aprovação da diretoria', completed: false, assignedTo: 'pietro' },
    ],
  },
  {
    id: 'proj-02',
    title: 'Setup IA Triagem WhatsApp — Clínica Brandão',
    clientName: 'Clínica Dr. Marcelo Brandão',
    serviceType: 'Inteligência Artificial',
    leadPartner: 'felipe',
    status: 'in_progress',
    deadline: '2026-10-18',
    progressPercent: 65,
    tasks: [
      { id: 't5', title: 'Mapeamento de perguntas frequentes e árvore de decisão clínica', completed: true, assignedTo: 'felipe' },
      { id: 't6', title: 'Conexão com API oficial WhatsApp Business', completed: true, assignedTo: 'felipe' },
      { id: 't7', title: 'Testes de prompt engineering e guardrails médicos', completed: false, assignedTo: 'felipe' },
      { id: 't8', title: 'Treinamento das secretárias no painel', completed: false, assignedTo: 'pietro' },
    ],
  },
  {
    id: 'proj-03',
    title: 'Estruturação de Tráfego Q4 — Nexus Capital',
    clientName: 'Nexus Capital Gestão de Recursos',
    serviceType: 'Paid Media',
    leadPartner: 'pietro',
    status: 'in_progress',
    deadline: '2026-10-25',
    progressPercent: 50,
    tasks: [
      { id: 't9', title: 'Análise de performance Q3 e descarte de criativos fatigados', completed: true, assignedTo: 'pietro' },
      { id: 't10', title: 'Novas copies com ângulos macroeconômicos e inflação', completed: true, assignedTo: 'felipe' },
      { id: 't11', title: 'Gravação e edição de criativos em vídeo', completed: false, assignedTo: 'pietro' },
      { id: 't12', title: 'Subida e testes de públicos Lookalike no Meta Ads', completed: false, assignedTo: 'pietro' },
    ],
  },
  {
    id: 'proj-04',
    title: 'Lote 80 Cartões NFC Metal — Vanguard',
    clientName: 'Vanguard Arquitetura',
    serviceType: 'VULTO TAP',
    leadPartner: 'pietro',
    status: 'planning',
    deadline: '2026-10-28',
    progressPercent: 20,
    tasks: [
      { id: 't13', title: 'Aprovação da prova digital de gravação a laser', completed: true, assignedTo: 'felipe' },
      { id: 't14', title: 'Configuração dos perfis digitais no servidor Vulto Tap', completed: false, assignedTo: 'felipe' },
      { id: 't15', title: 'Envio para usinagem e gravação física', completed: false, assignedTo: 'pietro' },
      { id: 't16', title: 'Expedição com embalagem premium customizada', completed: false, assignedTo: 'pietro' },
    ],
  },
];

export const INITIAL_BATCHES: VultoTapBatch[] = [
  {
    id: 'tap-201',
    clientOrProject: 'Grupo Aurora Real Estate',
    quantity: 120,
    cardType: 'Matte Black NFC',
    unitCost: 28.5,
    unitPrice: 81.6,
    status: 'delivered',
    destinationCity: 'São Paulo - SP',
    orderDate: '2026-09-15',
    tagsEnabled: true,
  },
  {
    id: 'tap-202',
    clientOrProject: 'Veritas Construtora',
    quantity: 40,
    cardType: 'Metal Black NFC',
    unitCost: 45.0,
    unitPrice: 125.0,
    status: 'delivered',
    destinationCity: 'Rio de Janeiro - RJ',
    orderDate: '2026-09-22',
    tagsEnabled: true,
  },
  {
    id: 'tap-203',
    clientOrProject: 'Vanguard Arquitetura (Amostra + Lote)',
    quantity: 80,
    cardType: 'Metal Black NFC',
    unitCost: 44.0,
    unitPrice: 130.0,
    status: 'engraving',
    destinationCity: 'Curitiba - PR',
    orderDate: '2026-10-04',
    tagsEnabled: true,
  },
  {
    id: 'tap-204',
    clientOrProject: 'Estoque Central Vulto Lab (Reserva)',
    quantity: 150,
    cardType: 'Matte Black NFC',
    unitCost: 24.0,
    unitPrice: 0,
    status: 'delivered',
    destinationCity: 'Santos - SP (Base)',
    orderDate: '2026-09-01',
    tagsEnabled: false,
  },
];

export const INITIAL_GOALS: GoalItem[] = [
  {
    id: 'g-1',
    title: 'Faturamento Mensal Outubro',
    target: 65000,
    current: 41200,
    unit: 'R$',
    category: 'Faturamento',
    deadline: '31/10/2026',
  },
  {
    id: 'g-2',
    title: 'Receita Recorrente Líquida (MRR)',
    target: 25000,
    current: 19400,
    unit: 'R$',
    category: 'Faturamento',
    deadline: '30/11/2026',
  },
  {
    id: 'g-3',
    title: 'Novos Contratos Fechados no Trimestre',
    target: 8,
    current: 5,
    unit: 'clientes',
    category: 'Clientes',
    deadline: '31/12/2026',
  },
  {
    id: 'g-4',
    title: 'Cartões VULTO TAP Ativos em Operação',
    target: 350,
    current: 240,
    unit: 'un',
    category: 'Vulto Tap',
    deadline: '31/12/2026',
  },
  {
    id: 'g-5',
    title: 'Margem Operacional Líquida',
    target: 65,
    current: 68.4,
    unit: '%',
    category: 'Eficiência',
    deadline: '31/10/2026',
  },
];

export const SERVICE_CATALOG: ServiceCatalogItem[] = [
  {
    id: 'sc-1',
    category: 'Aquisição & Tráfego',
    title: 'Paid Media — Gestão de Tráfego de Alta Performance',
    baseSetupPrice: 3500,
    suggestedMonthly: 4500,
    scopeSummary: 'Estruturação completa de funil de anúncios no Meta Ads, Google Ads e TikTok. Criação de criativos, testes contínuos de criativos, otimização de conversão e dashboards semanais.',
    deliverables: [
      'Auditoria de contas e tracking (Pixel, CAPI, GA4, GTM)',
      'Planejamento de esteira de criativos e ângulos de vendas',
      'Otimização diária de lances e alocação de verba',
      'Relatório analítico semanal com ROAS real e CAC',
    ],
    estimatedDeliveryDays: 7,
    marginPercent: 72,
  },
  {
    id: 'sc-2',
    category: 'Engenharia & Design',
    title: 'Sites & Sistemas — Desenvolvimento Web de Alta Conversão',
    baseSetupPrice: 8500,
    suggestedMonthly: 1200,
    scopeSummary: 'Desenvolvimento sob medida de Landing Pages, Sites Institucionais e Sistemas Web corporativos com performance extrema, design moderno, animações fluidas e SEO avançado.',
    deliverables: [
      'Design UI/UX exclusivo em Figma com alto contraste e estética premium',
      'Engenharia moderna (React, Vite, Next, TypeScript, Tailwind)',
      'Otimização de velocidade Core Web Vitals (90+)',
      'Integrações com Webhooks, CRM, WhatsApp e Checkout',
    ],
    estimatedDeliveryDays: 14,
    marginPercent: 68,
  },
  {
    id: 'sc-3',
    category: 'Persuasão & Mensagem',
    title: 'Copywriting & Narrativa Estratégica',
    baseSetupPrice: 4000,
    suggestedMonthly: 3000,
    scopeSummary: 'Construção da mensagem central que converte visitantes em clientes qualificados. Roteiros de VSL, copys de anúncios, páginas de captura e esteiras de e-mail marketing.',
    deliverables: [
      'Posicionamento de marca e refinamento de proposta de valor',
      'Roteiros para vídeos de vendas (VSL) e anúncios de alta retenção',
      'Copywriting completo de Landing Page e seções de conversão',
      'Sequência estratégica de follow-up e recuperação de leads',
    ],
    estimatedDeliveryDays: 5,
    marginPercent: 85,
  },
  {
    id: 'sc-4',
    category: 'Hardware & Networking',
    title: 'VULTO TAP — Cartões Físicos NFC Personalizados',
    baseSetupPrice: 2500,
    suggestedMonthly: 0,
    scopeSummary: 'Tecnologia de aproximação (NFC) para networking executivo de alto impacto. Cartões em metal ou matte black com gravação a laser personalizada e microsite digital integrado.',
    deliverables: [
      'Cartões físicos NFC em acabamento premium fosco ou metal nobre',
      'Gravação a laser personalizada da identidade visual do cliente',
      'Página de perfil digital responsiva com links e QR Code dinâmico',
      'Sem aplicativos: basta encostar em qualquer smartphone moderno',
    ],
    estimatedDeliveryDays: 10,
    marginPercent: 62,
  },
  {
    id: 'sc-5',
    category: 'Automação & IA',
    title: 'Inteligência Artificial — Agentes 24/7 & Automação de Atendimento',
    baseSetupPrice: 5500,
    suggestedMonthly: 1800,
    scopeSummary: 'Implantação de agentes inteligentes treinados no tom de voz da empresa para triagem, qualificação de leads, agendamento de reuniões e atendimento ininterrupto no WhatsApp.',
    deliverables: [
      'Agente configurado com base de conhecimento e diretrizes da marca',
      'Integração oficial via WhatsApp Cloud API e banco de dados',
      'Transferência inteligente para atendentes humanos quando necessário',
      'Painel de histórico de conversas e métricas de conversão',
    ],
    estimatedDeliveryDays: 12,
    marginPercent: 70,
  },
];

const STORAGE_KEY = 'vulto_lab_dashboard_state_v1';

export function loadDashboardState(): DashboardState {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (raw) {
      const parsed = JSON.parse(raw);
      return {
        currentUser: parsed.currentUser || 'felipe',
        transactions: parsed.transactions || INITIAL_TRANSACTIONS,
        deals: parsed.deals || INITIAL_DEALS,
        clients: parsed.clients || INITIAL_CLIENTS,
        projects: parsed.projects || INITIAL_PROJECTS,
        batches: parsed.batches || INITIAL_BATCHES,
        goals: parsed.goals || INITIAL_GOALS,
      };
    }
  } catch (err) {
    console.warn('Erro ao carregar estado do dashboard:', err);
  }

  return {
    currentUser: 'felipe',
    transactions: INITIAL_TRANSACTIONS,
    deals: INITIAL_DEALS,
    clients: INITIAL_CLIENTS,
    projects: INITIAL_PROJECTS,
    batches: INITIAL_BATCHES,
    goals: INITIAL_GOALS,
  };
}

export function saveDashboardState(state: DashboardState): void {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
  } catch (err) {
    console.error('Falha ao salvar estado do dashboard:', err);
  }
}

export function resetDashboardState(): DashboardState {
  const defaults: DashboardState = {
    currentUser: 'felipe',
    transactions: INITIAL_TRANSACTIONS,
    deals: INITIAL_DEALS,
    clients: INITIAL_CLIENTS,
    projects: INITIAL_PROJECTS,
    batches: INITIAL_BATCHES,
    goals: INITIAL_GOALS,
  };
  saveDashboardState(defaults);
  return defaults;
}
